# Generated by Django 3.2.9 on 2021-12-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211203_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='salary',
        ),
        migrations.AddField(
            model_name='room',
            name='payout',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
